organization:
    id: 8a46a8c5-0095-4a06-984a-682cb5cd51b7
    name: sodown4thecause
project:
    id: af2d2dab-5858-4a63-a709-02a0bd8268ff
    slug: gh/sodown4thecause/artificial-intelligentsia
    name: artificial-intelligentsia
